@Storage.API_HostAddress = http://localhost:5199

GET http://localhost:5199/api/melt
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEwMDMiLCJzdWIiOiJteVVzZXIiLCJmYW1pbHlfbmFtZSI6Ikl2YW5vdiIsIm5hbWUiOiJJdmFuIiwianRpIjoiYTUyZTY5Y2MtMjI0My00ZGQ0LWIwMjMtMWRkMDU3NTA5YTJjIiwicGVybWlzc2lvbiI6Ik1lbHQuVmlldyIsImV4cCI6MTc2NTM1OTI4MiwiaXNzIjoiU3RvcmFnZSIsImF1ZCI6IlN0b3JhZ2UifQ.0FJIAtWursZba3OOAZ9ad-HlH9KilrHnfVkZ4H1ZBUU
###

GET http://localhost:5199/api/user/1
Accept: application/json

###

POST http://localhost:5199/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer <your_jwt_token_here>

{
  "userName": "myUser",
  "password": "P@ssw0rd!",
  "surname": "Ivanov",
  "firstName": "Ivan",
  "middleName": "Ivanovich"
}

###

POST http://localhost:5199/api/authentication/login HTTP/1.1
Content-Type: application/json

{
  "userName": "myUser",
  "password": "P@ssw0rd!"
}

